# Generated by Django 4.2.6 on 2023-12-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_post_image5_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
