# Generated by Django 4.2.6 on 2023-12-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_post_title_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
