# Generated by Django 4.2.6 on 2023-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_category_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
