# Generated by Django 4.2.6 on 2023-12-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_category_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
    ]
