# Generated by Django 4.2.5 on 2023-10-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(default='', max_length=255)),
                ('heading1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content1', models.TextField(default='')),
                ('heading2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content2', models.TextField(default='')),
                ('heading3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content3', models.TextField(blank=True, default='', null=True)),
                ('heading4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content4', models.TextField(blank=True, default='', null=True)),
                ('heading5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content5', models.TextField(blank=True, default='', null=True)),
                ('heading6', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content6', models.TextField(blank=True, default='', null=True)),
                ('heading7', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content7', models.TextField(blank=True, default='', null=True)),
                ('heading8', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content8', models.TextField(blank=True, default='', null=True)),
                ('heading9', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content9', models.TextField(blank=True, default='', null=True)),
                ('heading10', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content10', models.TextField(blank=True, default='', null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('title_image', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image1', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image6', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image7', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image8', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image9', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('image10', models.ImageField(blank=True, default='', null=True, upload_to='post_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_best', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.author')),
                ('category', models.ManyToManyField(blank='true', to='articles.category')),
            ],
        ),
    ]
