# Generated by Django 4.2.6 on 2023-12-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_post_image10_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image5_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
